logging.level.org.springframework.security: DEBUG

spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://postgres-service:5432/eds
    name: eds
    username: postgres
    password: password
    test-on-borrow: true
    validation-query: SELECT 1
    data: classpath:data.sql
    # initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 2000000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: SpringBootJPAHikariCP
  jpa:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      hikari:
        registerMbeans: true
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      org:
        hibernate:
          envers:
            default_schema: data_audit
            global_with_modified_flag: true
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
application:
  google-map:
    apiKey: AIzaSyBSBO8X1EDGqmTz7Rz-wbqXrAIx39HWfsk
server:
  port: 8082
  servlet:
    session:
      cookie:
        http-only: true
        secure: true